### ISSUE TITLE
Future Features + Documentation

### ISSUE THREAD

**Issue by bearcanrun** [NomadGraphix/google-react-maps#3]
I'd love to keep contributing to this project. I'm game to start simply improving documentation or helping further expose/enable GMap API features. 

- Do you have a specific vision/goal for this project? 
- Already have a feature/todo list or other priorities to achieve?

In the meantime, I'm shoring up the datasets in my project and then I'll be integrating them deeper with this map component, so I will happily vest what I can back. I will of course continue to file issues/PR's as I dig in, but I will gladly accept any contribution guidance.

**Comment by NomadGraphix** [comment]
@bearcanrun I actually have this being used in production as well, so I will continue to contribute to this as long as my company exists. (https://hailtrace.com/app/maps/search)[https://hailtrace.com/app/maps/search]

So, my general goals for this project would be to see:

- A truly component driven google maps api integration into react in which each component is a black-box (or not completely library interdependent). In theory, a component could be just as easily added to a "non-react or partial-react" implementation of Google maps. 
- A useful mapping of react components that reflects the powerfully layered nature of the google maps api. ([See layers](https://developers.google.com/maps/documentation/javascript/layers))
- A specifically engineered DataLayer component that maps to and edits any GeoJSON object in the react way. (state + action => new state) The DataLayer is a key for my project because I want specific control over minute pieces of a GeoJSON object. 

As for a todos and specifics, let me add something within the README that gives you those details. I'm unsure of when I can exactly get to that. Of course, the vision is in my head right now and not on paper. I do think that it may be pretty obvious how I'm documenting the system, so you are welcome to perfect it as much as you see necessary. Also, if you discover bugs, feel free to do what you did earlier and I will be pretty quick to review them.

**Comment by NomadGraphix** [comment]
I added some of my vision.

**Comment by bearcanrun** [comment]
@NomadGraphix Wow, fabulous stuff! 

I resonate with all the items you've listed, especially a GeoJson DataLayer component. I feel Google was trying to start something similar with Fusion Tables, but the implementation is clunky and inelegant. 

The v2 implementation goals are directly under features I would use, so thank you for the focus and that's where I'll begin!

(PS I never thought that much about hail, but that's a really cool system)

**Comment by NomadGraphix** [comment]
Yeah, I hear you. I’m not sure fusion tables help me right now. That will probably be an edge requirement if we decide to add them to this library.

I also think Google could do a lot more with the GeoJSON standard. It has been especially frustrating using the DataLayer at times because DataLayer shapes are not the same as Shapes and their event systems are different.

**Comment by NomadGraphix** [comment]
Closing this for now.
